### ISSUE TITLE
Where is vector1.txt?

### ISSUE THREAD

**Issue by hsm207** [darrenyaoyao/ResCNN_RelationExtraction#2]
I get this error when running train.py:

> FileNotFoundError: [Errno 2] No such file or directory: '../data/vector1.txt'

Where can I get vector1.txt?

**Comment by darrenyaoyao** [comment]
You can extract the vector1.txt for vec.bin. I am sorry that I didn't put it in my code.
You can download it here: https://drive.google.com/open?id=0B-ZjKY509crKQXA0Y2FfbFJMY0E
Or try yo use Glove vector: https://nlp.stanford.edu/projects/glove/
